### ISSUE TITLE
Corresponding Plutus Haskell code for `parameterized_script.ts`

### ISSUE THREAD

**Issue by sourabhxyz** [spacebudz/lucid#104]
Hi, thanks for this amazing tool.

I was having trouble understanding [`parameterized_script.ts`](https://github.com/spacebudz/lucid/blob/main/src/examples/parameterized_script.ts), would appreciate if high level code (instead of low-level cbor hex) could also be given for the corresponding `mintingPolicy` validator.

Doubts which I believe would get clear once I see it: 
1. Usually, we get policy like so:
    ```haskell
    policy :: PaymentPubKeyHash -> Scripts.MintingPolicy
    policy someParam = mkMintingPolicyScript $
      $$(PlutusTx.compile [|| Scripts.wrapMintingPolicy . mkPolicy ||])
      `PlutusTx.applyCode`
      PlutusTx.liftCode someParam
    ```
    But [here](https://github.com/spacebudz/lucid/blob/main/src/examples/parameterized_script.ts#L24), was cbor hex obtained without giving any `applyCode` like above?
2. What is the role of `10n` parameter?

**Comment by alessandrokonrad** [comment]
> * But [here](https://github.com/spacebudz/lucid/blob/main/src/examples/parameterized_script.ts#L24), was cbor hex obtained without giving any `applyCode` like above?

Yes exactly. If you add applyCode then you serialize the script including the param. That's not what you want. You want to to serialize the script and apply the params yourself from Lucid.

Here's an example how you could achieve it in PlutusTx:

```hs
spendInstanceControl :: Scripts.Validator
spendInstanceControl = Api.Validator $ Api.fromCompiledCode ($$(PlutusTx.compile [|| wrap ||]))
  where
    wrap owner cs = Scripts.mkUntypedValidator $ spendValidatorControl (PlutusTx.unsafeFromBuiltinData owner) (PlutusTx.unsafeFromBuiltinData cs)
````

Validator signature:
 ```hs 
spendValidatorControl :: Api.PubKeyHash -> Api.CurrencySymbol -> ControlDatum -> ControlAction -> Api.ScriptContext -> Bool
```

`Api.PubKeyHash -> Api.CurrencySymbol` won't be applied to the serialized script and can be dynamically added from Lucid.


> What is the role of 10n parameter?

That's really just an example. The script takes an Integer as parameter.

**Comment by sourabhxyz** [comment]
Thanks a lot @alessandrokonrad!

If policy is not making any use of `10n` parameter, then I think it will help if example can mention it as dummy parameter (like ``// here `10n` is a dummy parameter to the script``).
