### ISSUE TITLE
Package does not work with next@latest (v. 13)

### ISSUE THREAD

**Issue by GGAlanSmithee** [spacebudz/lucid#106]
I've submitted an [issue](https://github.com/vercel/next.js/issues/41866) in the next.js repo, because the bug only appears once I updated to their latest build, but I'm reporting it here as well, because looking at [this code](https://github.com/spacebudz/lucid/blob/main/src/core/core.ts#L19) there might be an actual issue with setting `global.Headers` in node.js versions => 16.15.0, if it is readonly, as the error suggests: [documentation](https://nodejs.org/api/globals.html#class-headers). 

I've actually not been able to reproduce this in isolation, so might be nothing.

**Comment by GGAlanSmithee** [comment]
There is a bit of conversation going on in the linked issue. It looks like the issue is a more generic one, and that this project - in that case - is not compatible with node 18. Will check this out when I get time.

**Comment by MatiFalcone** [comment]
I am having the same issue.

**Comment by GGAlanSmithee** [comment]
@MatiFalcone check the linked issue for updates

**Comment by GGAlanSmithee** [comment]
@alessandrokonrad 

Maybe the fix is to conditionally polyfill only if not defined? I can send a PR for it

**Comment by GGAlanSmithee** [comment]
Looks like this is what next.js does

https://github.com/vercel/next.js/blob/227c35c0e281b38ff4f36b590624ffb802f5a8c7/packages/next/server/node-polyfill-fetch.js#L3

**Comment by GGAlanSmithee** [comment]
Sent a PR. No idea if this is correct or not though.

**Comment by GGAlanSmithee** [comment]
@alessandrokonrad @MatiFalcone 

I have updated [my example](https://github.com/GGAlanSmithee/cardano-lucid-blockfrost-proxy-example) with latest version of lucid (`0.7.0`) and next.js 13 and it works fine! The example if just sending a transaction, so I cannot account for more complex use cases, but atleast that one does work.

**Comment by markrufino** [comment]
@GGAlanSmithee stumbled upon this issue as well and reverted to `0.7.0` and it works. Thanks.
