### ISSUE TITLE
Cant sign data with unused eternl/typhon

### ISSUE THREAD

**Issue by Dazannah** [spacebudz/lucid#110]
hello, it would be nice, if i could get some help. i try to make a site with wallet authentication, i use lucid for it. the sign data work well with nami and flint. my problem is, if i try sign data with a never used eternl or typhon, the browser throw an error. i can sign with an eternl wallet that was used before. the cause i think is: when i want to write out the addy in browser consol, eternl return an empty value, so offcourse, lucid cant generate the stuff that it need from it. my question is: is there any work around or did i just miss someting?

it is not the end of world, but considering i want to use the authentication method for some web2 service, it is a possible scenario someone want to use it with a new wallet

the 1st error is what eternl give, th 2nd is typhon

![Screenshot from 2022-10-29 09-57-12](https://user-images.githubusercontent.com/39139379/198821007-62e4827c-0335-44ae-aa7e-c09fbea7a5bc.png)

**Comment by zachyking** [comment]
Just get the change address, either as fallback or directly.
```
const walletApi = await window.cardano[walletName].enable()
await walletApi.signData(walletApi.getChangeAddress(), hexData)
```

**Comment by Dazannah** [comment]
thanks for your answer
