### ISSUE TITLE
0.7.2 - Cannot read properties of undefined (reading 'getUtxosCore')

### ISSUE THREAD

**Issue by GGAlanSmithee** [spacebudz/lucid#114]
With the last change, I am getting this error after calling `switchProvider` followed by submitting a transaction. https://github.com/GGAlanSmithee/cardano-lucid-blockfrost-proxy-example can be used as a reproduction. Everything was working fine in 0.7.1 as far as I could tell.

**Comment by GGAlanSmithee** [comment]
Actually, the error persist after downgrading to 0.7.1 so might be an error on my end. WIll verify and ty to pin point it.

**Comment by GGAlanSmithee** [comment]
No, sorry again, the issue is only with 0.7.2, I had the version set to ^0.7.1, which 0.7.2 satisfies. Setting the version to 0.7.1 removes the error.

**Comment by GGAlanSmithee** [comment]
I guess the problem must be with this https://github.com/spacebudz/lucid/blob/main/src/lucid/lucid.ts#L117, but I don't see how exactly.

**Comment by alessandrokonrad** [comment]
Yes that's right. I added this line as a safety thing for now. When you switch provider you don't switch the wallet tho. 
So for now you have to reselect a wallet until I figure out an elegant solution for wallet.

**Comment by GGAlanSmithee** [comment]
Hi @alessandrokonrad thanks for your reply.

I see. I tried reverting the change to do what you exaplain; https://github.com/GGAlanSmithee/cardano-lucid-blockfrost-proxy-example/commit/9ef1224a58467ddf7d0dd195d9884d5bc81663d8 but I'm still seeing the same error though.

BTW, what's the reason for the last change?

```ts
this.wallet = lucid.wallet;
```

Wont `lucid.wallet` always be `undefined`, as it's a newly created lucid instance?

**Comment by alessandrokonrad** [comment]
> Wont `lucid.wallet` always be `undefined`, as it's a newly created lucid instance?

That's correct. That's what I want to achieve and force you to reselect a wallet. I don't want that someone accidentally builds a tx for mainnet while thinking he is on a testnet. I try to improve that, but for some wallet selection methods it's not that easy or obvious.

**Comment by GGAlanSmithee** [comment]
@alessandrokonrad 

I'm so stupid. I forget to `await` `switchProvider`.

See https://github.com/GGAlanSmithee/cardano-lucid-blockfrost-proxy-example/commit/3e4d42114637b5151d41eca6f75c27c0f4da61d0
