### ISSUE TITLE
Restrict access to only read assets

### ISSUE THREAD

**Issue by GGAlanSmithee** [spacebudz/lucid#118]
![image](https://user-images.githubusercontent.com/11805103/201946436-36e9b4e9-bc60-41a7-9287-e8635d2238a6.png)

@alessandrokonrad sorry if this question is out of scope for Lucid, but can't find the answer in anywhere cip-30-web-bridge related place.

Is it possible to only request read access? In this example, I only need read access, the user won't sign any transactions.

**Comment by alessandrokonrad** [comment]
Hey that's Nami related. I think it depends on how the wallet implements it or wants to implement it. It's possible, but I'm not sure if the effort is worth it. In order to give full approval for a tx you still have to confirm it with your wallet.

**Comment by GGAlanSmithee** [comment]
> Hey that's Nami related.

Ok, Thanks for clarifying!

> In order to give full approval for a tx you still have to confirm it with your wallet.

I agree that there's no harm for the user to accept those conditions since the wallet is only asking if it can request approval, not to actually approve anything - the user has to do that. It just stuck out to me a bit, but it might just be me being paranoid.

Thanks for the answer, I'll close this issue.
