### ISSUE TITLE
Verify a message without instantiating with a wallet?

### ISSUE THREAD

**Issue by rbmdotdev** [spacebudz/lucid#120]
I am looking at this example https://github.com/spacebudz/lucid/blob/65d589eeb3872c250b201d6326bb5678dcd0dc25/src/examples/sign_message.ts

and trying to figure out if I should be able to do the verifyMessage step without linking the lucid library to an in browser wallet?

the use case being using lucid to sign some user data in the browser and then sending that signed data to the server and using lucid to verify it was signed by the owner of an address stored in a database?

**Comment by micahkendall** [comment]
Use lucid.selectWalletFrom, like this
```js
const address = "...bech32...";
lucid.selectWalletFrom({address: address});
```
