### ISSUE TITLE
unable to find reference scripts

### ISSUE THREAD

**Issue by Bradley-Heather** [spacebudz/lucid#125]
As of this weekend all Transactions involving UTxOs with reference scripts attached are now failing on the preview network with the error 
`Uncaught (in promise) Redeemer (Spend, 1): Missing required script:`

This is true even for the [always_succeeds](https://github.com/spacebudz/lucid/blob/main/src/examples/always_succeeds.ts) example

**Comment by alessandrokonrad** [comment]
This has to do with db-sync changing the encoding of the script with different versions and blockfrost is always updating to their latest version. Lucid always expects doube cbor encoded scripts. I'm fixing that just right now and make sure single cbor encoded scripts are converted to double cbor encoded scripts and double encoded ones are left as they are.

**Comment by alessandrokonrad** [comment]
This should be resolved with Lucid 0.7.9
