### ISSUE TITLE
Advanced parsing into PlutusData?

### ISSUE THREAD

**Issue by lemmon-714** [spacebudz/lucid#126]
Imo it would be neat to be able to
1. specify expectations about incoming datums' shapes
2. parse arrays originally generated from record-types back into some kind of named shape

- Am I missing this existing already?
- Is it desirable for me to do it?

I would probably modify the Data class.

**Comment by alessandrokonrad** [comment]
I think that would be cool to have. Feel free to make a PR, then we can discuss it further👍🏻

**Comment by lemmon-714** [comment]
see https://github.com/spacebudz/lucid/pull/127
