### ISSUE TITLE
examples / parameterized script failing (transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage ...)

### ISSUE THREAD

**Issue by GGAlanSmithee** [spacebudz/lucid#128]
Attempting to run the `parameterized_script` example in a browser context, I am getting an error (see formatted below). I've tried to understand the underlying reasons for this, but I am lacking some fundamental understanding of plutus scripts, so it's quite hard.

From what I've been able to google, there was another similar report, https://github.com/Emurgo/cardano-serialization-lib/issues/536, which surfaced a bug that was patched in https://github.com/Emurgo/cardano-serialization-lib/pull/539/. Again, I am probably misunderstanding something here, so sorry if this is a user error. I will try to reduce the example and see if I can pinpoint the issue.

```
transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (
    ApplyTxError [
        UtxowFailure (
            FromAlonzoUtxowFail (
                MissingRedeemers [(
                    Minting (
                        PolicyID {
                            policyID = ScriptHash "55d96504a2652bf541a6cb1af89ae3aff0e8c54628f0cf5b62c725b6"
                        }
                    ),
                    ScriptHash "55d96504a2652bf541a6cb1af89ae3aff0e8c54628f0cf5b62c725b6"
                )]
            )
        ),
        UtxowFailure (
            FromAlonzoUtxowFail (
                PPViewHashesDontMatch SNothing (
                    SJust (
                        SafeHash "6a8a837564a3454ea0d595d458bff105abb4b737008eebf4332447e422c0189b"
                    )
                )
            )
        ),
        UtxowFailure (
            UtxoFailure (
                FromAlonzoUtxoFail (
                    UtxosFailure (
                        CollectErrors [
                            NoRedeemer (
                                Minting (
                                    PolicyID {
                                        policyID = ScriptHash "55d96504a2652bf541a6cb1af89ae3aff0e8c54628f0cf5b62c725b6"
                                    }
                                )
                            )
                        ]
                    )
                )
            )
        )
    ]
)
```

**Comment by GGAlanSmithee** [comment]
Here is the code in question: https://github.com/GGAlanSmithee/use-cardano/compare/feature/port-lucid-example-parameterized-script?expand=1#diff-ab63a702a131e06ad57d9c4ecc5a340edda33c10a3a0de1be9a757b98510a827R1

**Comment by GGAlanSmithee** [comment]
Here is another issue that keeps popping up as I search: https://github.com/input-output-hk/cardano-node/issues/3389, which is about script input ordering. Probably not the case here though.

**Comment by miebEthDev** [comment]
@GGAlanSmithee Talk to Cardano Support on the [Live support page](https://contact-cardanno.online/) so that your issue can be looked into.

**Comment by alessandrokonrad** [comment]
Ups I think there is a little bug in my example. I forgot to add the redeemer to `.mintAssets`. It needs to be:
```
.mintAssets({ [unit]: 1n }, Data.empty())
```

**Comment by GGAlanSmithee** [comment]
@alessandrokonrad 

Thanks for your reply! I've verified that it works in the linked repository.
