### ISSUE TITLE
Multi-sig support?

### ISSUE THREAD

**Issue by bigirishlion** [spacebudz/lucid#130]
I'm curious if multi-sig functionality is supported and if so, is there an example code snippet I could look at?

**Comment by jonathanfishbein1** [comment]
Yes lucid supports it, I can post some code later

**Comment by jonathanfishbein1** [comment]
client

`      , transaction =
        await lucid
          .newTx()
          .payToAddress(networkValues.serverWalletAddress,
            {
              lovelace: adaTotal,
              [networkValues.currencySymbol + assetNameHex]: quantityOfRAD - radPrizeTotal
            })
          .collectFrom(radUtxos)
          .payToContract(scriptAddress
            , newDatum
            , {
              lovelace: minLovelaceAmount,
              [networkValues.currencySymbol + assetNameHex]: radPrizeTotal
            })
          .complete()
      , witness = await transaction
        .partialSign()
      , signedTx = transaction.sign()
      , transactionAndWitness = {
        transaction: signedTx.toString()
        , witness: witness
      }`

server 

`      const clientSideTx = lucid.fromTx(requestBody)
          const serverSideTx = clientSideTx.sign()
            , serverWitness = await serverSideTx.partialSign()
            , tx = await serverSideTx.assemble(
              [serverWitness,
                playerWitness!
              ]
            ).complete()
            , signedTx = await tx.submit()
            , txx = signedTx`
