### ISSUE TITLE
Hardcoded value prevents use with testnets

### ISSUE THREAD

**Issue by jonathanfishbein1** [spacebudz/lucid#133]
https://github.com/spacebudz/lucid/blob/2c42cd886c2c4bc64bff8eee639e8805d8bb81fd/src/provider/blockfrost.ts#L54

**Comment by alessandrokonrad** [comment]
Hey I'm not sure what you mean exactly?

**Comment by jonathanfishbein1** [comment]
I'm using Lucid against the preview testnet but it looks like it's querying a mainnet address

`blockfrost.js:60          GET https://cardano-preview.blockfrost.io/api/v0/addresses/addr_vkh1ekt7trgums23tkhfjnwkpe3zypzslpdpg8n8xekqqzy3cqtmhjp/utxos?page=1 404`
