### ISSUE TITLE
examples that are interacting with smart contracts not working after v. 0.8.0

### ISSUE THREAD

**Issue by GGAlanSmithee** [spacebudz/lucid#134]
I am running regression testing, https://github.com/GGAlanSmithee/use-cardano/issues/68, and there are four examples, directly ported from Lucid, that are not working with the latest version of Lucid. These four examples are the exact ones that interacts with a smart contract.

The errors I am getting in version 0.8.1 are mixed, but I am seeing `FromAlonzoUtxoFail NoCollateralInputs` followed by a `InsufficientCollateral (Coin 0) (Coin 262791)`. I am 100% sure I have collateral set though. If I downgrade to version 0.8.0, all examples are working again.

 * lucid/always-succeed
 * lucid/matching-keyhash
 * lucid/matching-numbers
 * lucid/parameterized-script

**Comment by GGAlanSmithee** [comment]
There might be more to this than just the versioning, because it doesn't really make sense. Will continue testing and try to pinpoint the root cause.

**Comment by alessandrokonrad** [comment]
Hey try to upgrade to 0.8.2. There was a bug in 0.8.1 indeed...

**Comment by GGAlanSmithee** [comment]
Thanks @alessandrokonrad ! I can verify that all the tests are working now, and the typing system is great!
