### ISSUE TITLE
build failing(missing Node_modules)

### ISSUE THREAD

**Issue by leo42** [spacebudz/lucid#136]
I am trying to build Lucid so I can test some functionality I need for my project. 

I have tried building with "deno task build" on both windows and Linux and  I keep getting the same error message :

 [C:/......../lucid/node_modules](error: Uncaught (in promise) NotFound: The system cannot find the path specified. (os error 3), stat 'C:/....../node_modules/@typescript/lib-es2015/promise')
 
 I run npm update to install any missing packages but to no avail. Do I need to install any global dependencies, to get this working ?
 
 Also since I am taking up your time already would anyone object If I implement an interface for the "provider" :
 getTransactions(address: Address): Promise<Transaction[]>
 
 It should be able to work with blockfrost and Kupgmios.

**Comment by GGAlanSmithee** [comment]
@leo42 

works for me on latest commit on main, on win10

![image](https://user-images.githubusercontent.com/11805103/208447043-4b26529c-e439-44d6-a5ee-aa4e4eef4c48.png)
![image](https://user-images.githubusercontent.com/11805103/208447071-066babfb-6c09-4b0d-9ad4-979c06494bdf.png)
![image](https://user-images.githubusercontent.com/11805103/208447099-f03ebe89-6f80-4f0f-a6b7-8e972813ee78.png)

**Comment by leo42** [comment]
@GGAlanSmithee 
Versions seem to be up to date. 

![image](https://user-images.githubusercontent.com/4371293/208458044-aa7a51f8-d539-4f49-a5b5-efc74d22c8cb.png)

![image](https://user-images.githubusercontent.com/4371293/208458335-2c8919ec-5824-4235-adb6-6e574796a73a.png)

Its a run of the mill Windows mashing, I also tried on a linux machine to the exact same results. 

![image](https://user-images.githubusercontent.com/4371293/208458850-cc92be31-d53f-47ca-9b79-b73a0e7fabc3.png)

I probably messed something up, but I laterally just checked the out the code and run the build....... Not sure what is missing.

**Comment by GGAlanSmithee** [comment]
> checked the out the code and run the build

hmm, should just work AFAIK

**Comment by leo42** [comment]
> > checked the out the code and run the build
> 
> hmm, should just work AFAIK

Dam I was afraid of that, Was kind of hoping I was missing some dependency that was missing from the docs.

Thanks for helping out anw.

**Comment by GGAlanSmithee** [comment]
Idk but might be that you need typescript installed, i fint think so, but could be worth a try.

```
npm i -g typescript
```

**Comment by leo42** [comment]
Incase anyone runs into this in the future:

npm i -g deno
