### ISSUE TITLE
AWS amplify can not able to create lucid object. TypeError: Cannot read properties of null (reading 'TransactionBuilderConfigBuilder')

### ISSUE THREAD

**Issue by wishtree-gmakwana** [spacebudz/lucid#137]
**const lucid = await Lucid.new(
			new Blockfrost("https://cardano-preprod.blockfrost.io/api/v0/", "preProd5adsasadsadsadsaas"),
			"Preprod",
		);**
		
		Error :- TypeError: Cannot read properties of null (reading 'TransactionBuilderConfigBuilder')

**Comment by alessandrokonrad** [comment]
Seems like the wasm module is not loaded. Does AWS Amplify allow you to use WebAssembly?
