### ISSUE TITLE
500 Error while minting with a redeemer

### ISSUE THREAD

**Issue by jeffhappily** [spacebudz/lucid#143]
I'm getting an error while trying to mint some token, I'm not sure the root cause of this, but removing the redeemer argument from the `mintAssets` function call does fix this issue (ofc it introduces another error when I try to submit the tx, `MissingRedeemer`), so the issue seems to be related to the redeemer.

So the error comes from an API POST call to `https://cardano-preprod.blockfrost.io/api/v0/utils/txs/evaluate`, the payload is 

```
84a500818258209cf09788720d113a3d8bf0d0bb4809c81e0047257caffc6e1e6bbad9c17e11cc010182825839005d095b0f1065d61f245975cd8e1ec032e6242e3c0cbef2b48e3c889a58e2dff1e88b7e57bf6265bf684c0ca487b0dbc06e094a0a59d518c9821a00111958a1581c919d4c2c9455016289341b1a14dedf697687af31751170d56a31466ea1400182583900171b921e6e00004953b196e1ddd2e2434b1f41af1fe5e84ad2d422dfa5fd2a798a0961963400cb396605bd4dacddbbcb2279164d297ff0951b000000024b257cf7021a00029ee509a1581c919d4c2c9455016289341b1a14dedf697687af31751170d56a31466ea140010b58205b09f3819069340313c5e997b112443db61871cce52e43c2abf133b9f60c5936a20581840100d8798082000006814746010000224981f5f6
```
This is the smallest example I managed to replicate. And I receive a 500 error with the content of
```json
{
    "error": "Internal Server Error",
    "message": "An unexpected response was received from the backend.",
    "status_code": 500
}
```

Here's my source code

```ts
const tx = await lucid
    .newTx()
    .mintAssets(
      {
        [testPolicyId]: 1n,
      },
      Data.void()
    )
    .attachMintingPolicy(testMintingPolicy)
    .payToAddress(
      "addr_test1qpwsjkc0zpjav8eyt96umrs7cqewvfpw8sxtau453c7g3xjcut0lr6yt0etm7cn9ha5ycr9ys7cdhsrwp99q5kw4rrysk7fd7x",
      {
        [testPolicyId]: 1n,
      }
    )
    .complete({ nativeUplc: false });
```
and the minting policy is just an always success minting policy.

**Comment by mmahut** [comment]
@jeffhappily do you mind to try now, please?

**Comment by jeffhappily** [comment]
It seems to be working now! May I know what's the issue?

**Comment by mmahut** [comment]
@jeffhappily one of the Blockfrost's Ogmios instances on preprod were misbehaving. We are sorry for the trouble it has caused.

**Comment by jeffhappily** [comment]
No worries, thanks for helping with this!
