### ISSUE TITLE
Delegation for Nativescript reward address failing(RuntimeError: unreachable)

### ISSUE THREAD

**Issue by leo42** [spacebudz/lucid#147]
I have tried to delegate Multisig wallets using Lucid.  And I always get the same error (Uncaught (in promise) RuntimeError: unreachable)

I have tried  using native scripts containing only staking keys , and I have tired with native scripts containing only payment keys(regular multiset wallets) For my last Iteration I extracted the prosses for the delegation certificate and used the Cardano_multiplatform_lib to generate the delegation certificate. 

Example of latest Iteration: 

`
async createDelegationTx(pool, signers){ 

      const rewardAddress =  this.lucid.utils.validatorToRewardAddress(this.lucidNativeStakingScript)
      if (!this.checkSigners(signers)){
        console.log("Not enough signers")
        return "Not enough signers"
      }

      const tx = this.lucid.newTx()

      signers.map( value => (
        tx.addSignerKey(value)
      ))
      
      tx.payToAddress(this.getAddress(),{lovelace: 5000000})
       // .delegateTo(rewardAddress,pool)
      .attachSpendingValidator(this.lucidNativeScript)
      .attachWithdrawalValidator(this.lucidNativeStakingScript)
      .registerStake(rewardAddress)
   
   
      const uint8Array = new Uint8Array(this.lucid.utils.validatorToScriptHash(this.lucidNativeStakingScript).match(/.{2}/g).map(byte => parseInt(byte, 16)));

          tx.txBuilder.add_certificate(C.Certificate.new_stake_delegation(
          C.StakeDelegation.new( C.StakeCredential.from_scripthash(
            C.ScriptHash.from_bytes(uint8Array)  
          ),
          C.Ed25519KeyHash.from_bech32(pool)  
      )))

      const completedTx =await tx.complete()
      
     this.pendingTxs.push({tx:completedTx, signatures:[]})

      return "Sucsess"
    }
`

The full error is : 
Uncaught (in promise) RuntimeError: unreachable
    at be0a52a3b82858638123.wasm:0x173d87
    at be0a52a3b82858638123.wasm:0x21f316
    at be0a52a3b82858638123.wasm:0x21c1f5
    at be0a52a3b82858638123.wasm:0x1bf53f
    at TransactionBuilder.add_certificate (cardano_multiplatform_lib.js:13235:10)
    at Wallet._callee7$ (Wallet.js:638:107)
    at tryCatch (Wallet.js:17:1357)
    at Generator.eval (Wallet.js:17:4174)
    at Generator.eval [as next] (Wallet.js:17:2208)
    at asyncGeneratorStep (Wallet.js:18:103)
    
 Please help, I am not sure if this is a lucid issue or an implementation problem. 
 I have tried several workarounds (using only payment keys for the native script, using only staking keys for the native script, creating the delegation certificate from scratch) and nothing seems to help;

 
 If we figure out a fix I will happily implement it in lucid and open a pull request.

**Comment by alessandrokonrad** [comment]
Hey I found the root cause and just fixed it. Creating a new release very soon. For now you can just build from the main branch and see if it works for you.

**Comment by leo42** [comment]
I am already on a custom fork. 

Thank you so much.

**Comment by leo42** [comment]
Confirmed The error is gone an the transaction is generated.

Thank  you again.
