### ISSUE TITLE
Provider discrepancies 

### ISSUE THREAD

**Issue by leo42** [spacebudz/lucid#148]
Implementing Provider switching I found the Blockfrost and Kupmios behave differently when querying the Utxos of an address.  

when using Blockfrost : 

Query using a Address : returns the Utxos of that specific address
Query using a Credential: returns the Utxos of all addresses that are derived from that credential

When Using Kupmios :
Query using a Address : returns the Utxos of all addresses that are derived from the same credential 
Query using a Credential: returns error: "No address type matched for: [object Object]"

as an example the following code works the same for my app independent of provider : 

`  

       const credential = "kupoUrl" in this.lucid.provider ? this.getAddress() : this.lucid.utils.getAddressDetails(this.getAddress()).paymentCredential
      this.utxos = await this.lucid.provider.getUtxos(credential)`
      
by changing the credential to a raw address Kupmios gives the same results as Blockfrost.

I have tried hard-coding the credentials hex in the Kupmios implementation and that works just fine. 

I am not sure at what point of the code It tries to derive the address type for the credential.

**Comment by alessandrokonrad** [comment]
> Query using a Address : returns the Utxos of all addresses that are derived from the same credential

This is from the Kupo docs and this is how you query utxos by a specific address:
```
http://localhost:1442/matches/addr1vyc29pvl2uyzqt8nwxrcxnf558ffm27u3d9calxn8tdudjgz4xq9p
```
That's exactly what happens in Lucid too:
https://github.com/spacebudz/lucid/blob/1ee48a5d536f25a9b0e2c70f7ef47da2ca71ab91/src/provider/kupmios.ts#L86-L90

> Query using a Credential: returns error: "No address type matched for: [object Object]"

Are you sure you are on one of the latest Lucid versions? I'm just confused that Blockfrost allows you to query by payment credential, but I introduced that at the same time for the Kupmios provider too. This is what confused me, but I cannot reproduced this exact error and in general everything is working fine for me.

**Comment by leo42** [comment]
> Are you sure you are on one of the latest Lucid versions? I'm just confused that Blockfrost allows you to query by payment credential, but I introduced that at the same time for the Kupmios provider too. This is what confused me, but I cannot reproduce this exact error and in general everything is working fine for me.

Yes my local branch is up to data with the lucid Main

Things that might be different in my environment: 
A) I am calling lucid inside a Js file(not Ts ) script 

I checked the Kupmios implementation, It does seem to be perfectly in sync with what the Kupo docs say. Not sure why I returns  UTXOs that belong to other addresess with the same credential(NativeScript)

Here is an example of a Credentials that throw an error in Kupmios but works for Blockfrost

{type: 'Key', hash: '28466de8c30a02906b398cecb7d80d15613407a8e046d39b5bf1db28'} 
{type: 'Script', hash: 'cd91656179c8cbb34b80722acc9cc74149d273e624885daacb1569b5'}

So I can confirm that this happens both for simple address and for Script Credentials.

**Comment by leo42** [comment]
Can you give it a try with this address on Preprod ? 

"addr_test1xrxezetp08yvhv6tspez4nyucaq5n5nnucjgshd2ev2kndwdj9jkz7wgewe5hqrj9txfe36pf8f88e3y3pw64jc4dx6s7cmkvx"

On my side it returns Utxos for [addr_test1xrxezetp08yvhv6tspez4nyucaq5n5nnucjgshd2ev2kndwdj9jkz7wgewe5hqrj9txfe36pf8f88e3y3pw64jc4dx6s7cmkvx,
addr_test1xrxezetp08yvhv6tspez4nyucaq5n5nnucjgshd2ev2knd2c5s90hsth0fxd3ce82ml9hjjepkrmvjyv6pakkjnk6fcs8d9x2m]

**Comment by leo42** [comment]
I found the underline issue, Embarrassing story.....
Sorry for bothering you needlessly, closing now
