### ISSUE TITLE
Promise.all for loading wasm

### ISSUE THREAD

**Issue by SebastienGllmt** [spacebudz/lucid#155]
I noticed that in https://github.com/spacebudz/lucid/blob/main/src/core/core.ts modules are loaded sequentially. In Flint, we noticed that at least for us use Promise.all for loading the modules led to a 10% faster startup time

**Comment by alessandrokonrad** [comment]
Hey @SebastienGllmt thanks for the hint. So your suggestion is to change it to something like this:
```js
const [resolvedC, resolvedMsg] = await Promise.all([
  importForEnvironmentCore(),
  importForEnvironmentMessage(),
]);

export const C: typeof Core = resolvedC!;

export const M: typeof Msg = resolvedMsg!;
```
Am I getting this right?
