### ISSUE TITLE
"Uncaught (in promise) Missing input or output for some native asset"

### ISSUE THREAD

**Issue by ElCidCampeon** [spacebudz/lucid#156]
Haven't heard back from our dev in quite some time and was hoping someone could help provide a solution to this issue when trying to deposit/withdraw tokens off our dapp. Seems to occur more with Nami wallets.  Once your wallet experiences this issue it can no longer deposit or withdraw our token.

![image](https://user-images.githubusercontent.com/97695658/219079255-3ad2a3a0-5d7b-46d4-af05-cf855bf48b7c.png)

**Comment by alessandrokonrad** [comment]
It's not very helpful to paste in your entire logic here. But `missing input or output for some native assets` and `InputsExhaustedError` mean that either the wallet doesn't have a certain asset or not enough of it.

**Comment by ElCidCampeon** [comment]
Sorry not well versed with this.   I'll remove all the code.  As I mentioned before we haven't been able to reach the dev we hired to create this for our games.  

Is there any issue with Nami wallets recognizing native tokens?  I'm having issues with 2 of my wallets using Nami and they certainly have enough ADA and tokens.

**Comment by alessandrokonrad** [comment]
> Is there any issue with Nami wallets recognizing native tokens? I'm having issues with 2 of my wallets using Nami and they certainly have enough ADA and tokens.

Not that I'm aware of. Your dev should check the UTxOs Nami returns, then you know if it's a Nami issue, Lucid issue or an issue in your own code.

**Comment by ElCidCampeon** [comment]
How can I do that.  Doubtful we will ever hear from him again.

**Comment by ElCidCampeon** [comment]
Tx's aren't even going through now.  Again only with certain wallets when previously they had no issues connecting, depositing or withdrawing.
