### ISSUE TITLE
Question: signing with Fireblocks

### ISSUE THREAD

**Issue by dvanderbeek** [spacebudz/lucid#161]
Hi! I was wondering if anyone has experience using Lucid to build transactions and signing them with Fireblocks. I am getting an error when I try to pass the signature from Fireblocks into the `assemble` function and am a bit stumped because I can't figure out a way to tell what's different between the signature they give you vs. the one you get using the `partialSign` function in lucid. The error I'm seeing is below:

<img width="669" alt="image" src="https://user-images.githubusercontent.com/828182/221625943-39e1a2ae-3045-4714-9617-fe8b7de0e64e.png">

**Comment by alessandrokonrad** [comment]
Hey, could you post a signature from Fireblocks here? Then it's easier to tell what's wrong.

**Comment by dvanderbeek** [comment]
Here's a signature from Fireblocks:

c12c611e62ead716cb6bcace582e1b47fd2755d07de70bab1302a4ceb9829a12c156c6453beaf9c75dcf49e470469deec5501951d5bfbd5dff67a840743b9406

The transaction hash that was signed is `63ae81fc1beb80504d3a15a6c997433d9b510d628cc69e7a157d1640d7689edd`

Let me know if you need any other information

**Comment by alessandrokonrad** [comment]
> c12c611e62ead716cb6bcace582e1b47fd2755d07de70bab1302a4ceb9829a12c156c6453beaf9c75dcf49e470469deec5501951d5bfbd5dff67a840743b9406

This seems to be just a plain Ed25519 signature. This is not enough information for the witness set. You need the vkey/public key as well that belongs to the signature. 

Let's say you have the vkey as well then you could do the following:

```js
import { C, fromHex, toHex } from "lucid-cardano"; 
const w = C.TransactionWitnessSet.new();
const vkeys = C.Vkeywitnesses.new();
vkeys.add(
  C.Vkeywitness.new(
    C.Vkey.from_bytes(fromHex("<vkey>")),
    C.Ed25519Signature.from_hex("<signature>"),
  ),
);
w.set_vkeys(vkeys);
const txWitnessSet = toHex(w.to_bytes());
//...
tx.assemble([txWitnessSet]);
//...
```

**Comment by dvanderbeek** [comment]
> > c12c611e62ead716cb6bcace582e1b47fd2755d07de70bab1302a4ceb9829a12c156c6453beaf9c75dcf49e470469deec5501951d5bfbd5dff67a840743b9406
> 
> This seems to be just a plain Ed25519 signature. This is not enough information for the witness set. You need the vkey/public key as well that belongs to the signature.
> 
> Let's say you have the vkey as well then you could do the following:
> 
> ```js
> import { C, fromHex, toHex } from "lucid-cardano"; 
> const w = C.TransactionWitnessSet.new();
> const vkeys = C.Vkeywitnesses.new();
> vkeys.add(
>   C.Vkeywitness.new(
>     C.Vkey.from_bytes(fromHex("<vkey>")),
>     C.Ed25519Signature.from_hex("<signature>"),
>   ),
> );
> w.set_vkeys(vkeys);
> const txWitnessSet = toHex(w.to_bytes());
> //...
> tx.assemble([txWitnessSet]);
> //...
> ```

Ah, okay that is super helpful. We do get the public key as part of the Fireblocks response - what would be the equivalent code snippet assuming we have that and not the vkey?

**Comment by dvanderbeek** [comment]
Okay thanks, this is very helpful. I'm still running into an error, but it's a different one this time. With the following inputs:

signature: `7c9af540cfbc89953e2997ca5562810fdf6df3d6c173e782f6fadf9f15b2c8889a249da983d4e1bb462e31723aa08d2d8e8567810e12b538a0ec2c559e244a0a`
public key: `9c9f6d340fab44895406405d5c50fa480b59dafda5f38649f7a2d53ebbb5a7d1`

and the code you provided, I'm getting this error:

```
Error: Deserialization: Invalid cbor: not the right type, expected `Bytes' byte received `Array'.
```

which I think is happening when it hits `C.Vkey.from_bytes(fromHex("9c9f6d340fab44895406405d5c50fa480b59dafda5f38649f7a2d53ebbb5a7d1"))`

Any idea why? Thanks so much for the help!

**Comment by dvanderbeek** [comment]
I think I got it:

```
const keyBytes = fromHex("9c9f6d340fab44895406405d5c50fa480b59dafda5f38649f7a2d53ebbb5a7d1")
const key = C.PublicKey.from_bytes(keyBytes)
const vkey = C.Vkey.new(key)
```

**Comment by dvanderbeek** [comment]
@alessandrokonrad thanks again for your help! I have one follow-up question - is there a way to derive the pubkey that belongs to the signature from an account address?

**Comment by alessandrokonrad** [comment]
You can only derive the `pubkey hash` from an address. You need the private key or the extended public key to derive the actual `public key` of an address.
