### ISSUE TITLE
Unable to deserialize transaction hex for multi-sig NFT minting transaction when using IPFS CIDv1 identifier in the metadata

### ISSUE THREAD

**Issue by DearDisaster** [spacebudz/lucid#162]
Occurs when using the fromTx() function and passing the prebuilt transaction hex. The same code is successful every time when using a CIDv0 identifier. There appears to be a string length limitation somewhere in the pipeline that throws the following error due to the length of the CIDv1 identifier:

mod.js:2 Uncaught Deserialization failed in Transaction.auxiliary_data.AuxiliaryData.metadata.GeneralTransactionMetadata.MetadataMap.MetadataMap.MetadataMap because: Metadata error: JsValue("Max metadata string too long: 66, max = 64")

Example CIDv1:
ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi

**Comment by alessandrokonrad** [comment]
What tool/library did you use the build the tx in the first place? Text strings in metadata cannot exceed 64 characters. If your text exceeds 64 charactes then you need to convert the text into an array of 64 character chunks.

**Comment by DearDisaster** [comment]
Yep, my mistake, I see the 64 byte max in the docs now. Makes sense.

The original transaction was built using CardanoSharp-Wallet. Seems there's nothing on their side to catch the metadata string length issue. Also worth noting that pool.pm metadata test does not catch the issue either. Leading me to believe the metadata was correct.

Example:
https://pool.pm/test/metadata?metadata=%257B%2522721%2522%253A%257B%25228f750907dcabceec6c2f6e49fdef54cdf9f6958e69504f500fd667e3%2522%253A%257B%2522AN-984581458%2522%253A%257B%2522name%2522%253A%2522AN-984581458%2522%252C%2522description%2522%253A%2522AN-984581458%2522%252C%2522image%2522%253A%2522ipfs%253A%252F%252Fbafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi%2522%252C%2522mediaType%2522%253A%2522image%252Fpng%2522%252C%2522attributes%2522%253A%257B%2522BodyColor%2522%253A%2522White%2522%252C%2522MagicColor%2522%253A%2522None%2522%252C%2522FloorAccessory%2522%253A%2522Brown%2522%252C%2522SkyColor%2522%253A%2522Brown%2522%257D%252C%2522files%2522%253A%255B%255D%252C%2522website%2522%253A%2522ok%2522%257D%257D%252C%2522version%2522%253A%25221.0%2522%257D%257D

Good news though, I updated the code to break the strings into 64 character max chunks and it worked like a charm!

Thanks for sending me in the right direction.
