### ISSUE TITLE
Wallet interface `getUTxOs` accepts no parameters

### ISSUE THREAD

**Issue by mateusap1** [spacebudz/lucid#163]
[CIP-0030](https://cips.cardano.org/cips/cip30/#apigetutxosamountcborvalueundefinedpaginatepaginateundefinedpromisetransactionunspentoutputnull) defines the `getUTxOs` function as possibly receiving two arguments (amount and paginate). This is quite useful when building transactions because it means wallets can natively use their own coin selection algorithm to provide you with the right UTxOs and this does not require any form of external provider (ogmios / kupo or blockfrost) except the one the wallet uses natively.

The problem however is that in Lucid's API, the [`Wallet`](https://deno.land/x/lucid@0.9.4/mod.ts?s=Wallet#method_getUtxos_2) interface exposes a `getUTxOs` function which accepts no arguments. Forcing a developer who want's to make his program more efficient to use the native `window.cardano` approach or do the coin selection using lucid (which can be quite inefficient if the user has multiple UTxOs and the wallet has to return all of them).

**Comment by alessandrokonrad** [comment]
> does not require any form of external provider (ogmios / kupo or blockfrost) except the one the wallet uses natively

This is already the case when you get the utxos from the browser wallet.

> Forcing a developer who want's to make his program more efficient to use the native window.cardano approach or do the coin selection using lucid (which can be quite inefficient if the user has multiple UTxOs and the wallet has to return all of them).

A browser wallet doesn't perform coin selection when requesting utxos from it through the dApp connector. It's only filtering, not coin selection. You have to perform coin selection anyway in Lucid. I'm not really sure about the perfomance benefits here.

Besides that it breaks compatibility with other wallet types in Lucid. I like to keep it consistent and easy.
