### ISSUE TITLE
No message from 'traceIfFalse'

### ISSUE THREAD

**Issue by adam-young-dev** [spacebudz/lucid#166]
My validator is like:

```
mkValidator :: BuiltinData -> BuiltinData -> ScriptContext -> Bool 
mkValidator _ _ _ = traceIfFalse "--Message Here--" False
```

In version 0.9.3 when the validator returns false, the message from `traceIfFalse` in the contract appears in the console like:

```
ExBudget {
    mem: 13462310,
    cpu: 9831109018,
}

--Message Here--
PT5
```
This makes it easy to debug. But now in version 0.9.4 that message is gone. Not showing.

**Comment by alessandrokonrad** [comment]
This is probably related to Aiken. How does the full error message look now?

**Comment by adam-young-dev** [comment]
v0.9.3

```
Redeemer (Spend, 0): The provided Plutus code called 'error'.

ExBudget {
    mem: 13462310,
    cpu: 9831109018,
}

--Message Here--
PT5
```

v0.9.4

`Redeemer (Spend, 0): The provided Plutus code called 'error'.`

**Comment by adam-young-dev** [comment]
I try v0.9.4 with a simple validator in Aiken:

```
validator spend {
  fn(datum: Data, redeemer: Data, context: Data) -> Bool {
    trace @"--Message Here--"
    False
  }
}
```

Same result. Not showing.

**Comment by alessandrokonrad** [comment]
I forwarded this to the guys behind Aiken. Pretty sure it's related to their recent changes.
