### ISSUE TITLE
Lucid doesn't work with reactJS apps.

### ISSUE THREAD

**Issue by lenoteddy** [spacebudz/lucid#169]
It works on development environment.
But, when I build a react app, it shows blank screen & I saw no error at browser console.
I use react version "^17.0.2".

**Comment by GGAlanSmithee** [comment]
I think we need a bit more info to be able to help you. I have used lucid-cardano with react for a long while. See this as an example https://github.com/use-cardano/use-cardano

**Comment by web3-literally** [comment]
> I think we need a bit more info to be able to help you. I have used lucid-cardano with react for a long while. See this as a reference example https://github.com/use-cardano/use-cardano

I also met same issues, but I converted project to webpack style and configured, now it works

**Comment by lenoteddy** [comment]
Yes, I think it needs to setup using webpack.
I will close this issue.
