### ISSUE TITLE
utxosAt only returns the first UTXO

### ISSUE THREAD

**Issue by wailokmonad** [spacebudz/lucid#184]
As mentioned in the title, Lucid.utxosAt() only returns the first UTXO.

**Comment by wailokmonad** [comment]
https://preprod.cardanoscan.io/address/addr_test1wzkevesc9wvaxfy63cxuksq95c674wpe9qcg6murm9tsgcq726eds?tab=transactions

This is my script address. As you can see, there should be more than one UTXOs sitting

**Comment by wailokmonad** [comment]
const [scriptUtxo] = await lucid.utxosAt("addr_test1wzkevesc9wvaxfy63cxuksq95c674wpe9qcg6murm9tsgcq726eds");

This is my code

**Comment by alessandrokonrad** [comment]
I don't fully understand the issue. 
Obviously when you do this: 
```js
const [scriptUtxo] = await lucid.utxosAt("addr_test1wzkevesc9wvaxfy63cxuksq95c674wpe9qcg6murm9tsgcq726eds");
```
then it's just one utxo because you pattern match it.
If you do this you see a list of UTxOs:
```js
const scriptUtxos = await lucid.utxosAt("addr_test1wzkevesc9wvaxfy63cxuksq95c674wpe9qcg6murm9tsgcq726eds");
```

**Comment by wailokmonad** [comment]
Oh, sorry. My bad.
