### ISSUE TITLE
 No "exports" main defined in */node_modules/lucid-cardano/package.json

### ISSUE THREAD

**Issue by Anil-akb** [spacebudz/lucid#186]
The Lucid Cardano package.json file is missing the "exports" main definition, which is causing errors when trying to use the module in a project.

Relevant Information:

Package Name: Lucid Cardano
Package Repository: https://github.com/lucid-outcomes/lucid-cardano
Error Message: "No 'exports' main defined in /node_modules/lucid-cardano/package.json"
Node.js version: [Iv16.20.0]
NPM version: [8.19.4]
Steps to Reproduce:

Create a new Node.js project.
Install Lucid Cardano module using NPM: npm install lucid-cardano
Import Lucid Cardano module in your code: import {Lucid} = from 'lucid-cardano';
Run your code with Node.js: node index.js
Observe the error message: "No 'exports' main defined in /node_modules/lucid-cardano/package.json"

**Comment by web3-literally** [comment]
I also met same issues for my node js typescript backend code, please help me to resolve this isssues.

**Comment by web3-literally** [comment]
> 

Until the lucid team resolve this issue, if you are urgent to make transaction on cardano, 
you can use the Mesh package

https://meshjs.dev/apis/transaction

**Comment by Anil-akb** [comment]
I have resolved the issues.

**Comment by web3-literally** [comment]
> I have resolved the issues.

How did you resolve that?

**Comment by Anil-akb** [comment]
{
  "compilerOptions": {
    "target": "ES2022",

    /* Modules 2020 change to 2022*/
    "module": "ES2022",
    "moduleResolution": "node",

    "allowJs": true,

    "esModuleInterop": true,

    "strict": false,

    "skipLibCheck": true
  },
  "ts-node": {
    "esm": true,
    "experimentalSpecifierResolution": "node"
  }
}


Adding this code in ts.config.json file

**Comment by web3-literally** [comment]
> { "compilerOptions": { "target": "ES2022",
> 
> ```
> /* Modules 2020 change to 2022*/
> "module": "ES2022",
> "moduleResolution": "node",
> 
> "allowJs": true,
> 
> "esModuleInterop": true,
> 
> "strict": false,
> 
> "skipLibCheck": true
> ```
> 
> }, "ts-node": { "esm": true, "experimentalSpecifierResolution": "node" } }
> 
> Adding this code in the tsconfig.json file

Thanks so much
