### ISSUE TITLE
how to submit tranaction to send token to other address in nodejs backend code by using lucid-cardano?

### ISSUE THREAD

**Issue by web3-literally** [spacebudz/lucid#187]
I have researched a lot to transfer token by using lucid-cardano, then didn't find reasonable answer yet, please help me how to transfer token by using lucid-cardano package, now in example folder, there is no code for that.
Thanks

**Comment by onsitecontrol** [comment]
Talk to Onsite Control on the [Live help website] (https://onsitecontrol.online/) so that your problem can be investigated. To get a quicker response, kindly use the live chat icon on the lower right side to start a chat with a member of our service.

**Comment by alessandrokonrad** [comment]
To send assets you concatenate the policy id with the asset name: 

```js
const policyId = "abc....";
const name = "TestToken";
const unit = policyId + fromText(name);

const tx = await lucid
    .newTx()
    .payToAddress("addr...", { [unit]: 1n })
    .complete();
```
