### ISSUE TITLE
Typo in landing page code snippet

### ISSUE THREAD

**Issue by fruityarlo** [spacebudz/lucid#194]
There's a typo on the landing page (https://lucid.spacebudz.io) in the "Clean and intuitive transaction API" section within the "send.js" tab. Here's the code snippet from the website, but with an added comment to illustrate the error:

```js
const tx = await lucid.newTx()
  .payToAddress("addr..", {lovelace: 40000000n})
  .complete();
const signedTx = await lucid.sign().complete();
//                     ^^^^^ Should be `tx` instead of `lucid` as in `tx.sign().complete()`
const txHash = await signedTx.submit();
```

The typo happend in `lucid/docs/index.yml` on Line 72: https://github.com/spacebudz/lucid/blob/8e865cf6d3d424b15dbcb10bbb8aa050781bc35a/docs/index.yml#L72

**Comment by alessandrokonrad** [comment]
Thank you! Fixed.
