### ISSUE TITLE
Bundle uploaded to NPM didn't go through packaging process?

### ISSUE THREAD

**Issue by eddiemundo** [spacebudz/lucid#256]
The packaging process for `0.10.8` didn't seem upload the bundle to NPM the same way it did for `0.10.7`?

It results in code not being able to find the `lucid-cardano` module.

**Comment by hgextracts** [comment]
having same issue tried to uninstall and install v0.10.7 and still have same issue

**Comment by alessandrokonrad** [comment]
Thanks for letting me know guys. Published indeed the wrong parts accidentally... `0.10.9` should fix this again, let me know if it works for you.

**Comment by eddiemundo** [comment]
It does work. Thank you!
