### ISSUE TITLE
Lucid - Transaction building problem after Chang Hardfork 

### ISSUE THREAD

**Issue by CardanoTokenIO** [spacebudz/lucid#259]
This issue pops when using lucid to interact with smart contract transactions after the chang hardfork

error TxSendError: (400)
failed:
13840561edcbf6a108909bb8729a7c041229e63ed84e349c6e1333fc95409511
Insufficient fee! The transaction doesn't not contain enough fee to cover the minimum required by the protocol. Note that fee depends on (a) a flat cost fixed by the protocol, (b) the size of the serialized transaction, (c) the budget allocated for Plutus script execution. The field 'data.minimumRequiredFee' indicates the minimum required fee whereas 'data.providedFee' refers to the fee currently supplied with the transaction.
Data: {"minimumRequiredFee":{"ada":{"lovelace":579561}},"providedFee":{"ada":{"lovelace":306650}}}

**Comment by AI-Master-Solutions** [comment]
@CardanoTokenIO Hi There!, mind sharing how did you solve that issue? I'm having the same issues with the stablecoin example on the plutus pionner program when I try to mint new coins
