### ISSUE TITLE
How do we construct a TX output with  --tx-out-datum-embed-file in Lucid?

### ISSUE THREAD

**Issue by judeebene** [spacebudz/lucid#34]
I have a got a TX with --tx-out-datum-embed-file?

 is payToAddressWithDatum the right function to call.
 
The full TX in Cardano-cli is 
```
cardano-cli transaction build \
  --alonzo-era \
  $BLOCKCHAIN \
  --tx-in $utxoScript \
  --tx-in-script-file $nftValidatorFile \
  --tx-in-datum-file $datumFile \
  --tx-in-redeemer-file $redeemerFile \
  --required-signer $signingKey \
  --tx-in-collateral --address $spenderAddress $BLOCKCHAIN ) \
  --tx-out "$scriptHash + $output1 + $amount lovelace" \
  --tx-out-datum-hash $outDatumHash \
  --tx-out-datum-embed-file $outDatumFile \
  --tx-out "$spenderAddress + 3000000 lovelace $extraOutput" \
  --change-address $spenderAddress \
  --protocol-params-file $baseDir/$BLOCKCHAIN_PREFIX/protocol-parameters.json \
  --invalid-before $startSlot \
  --invalid-hereafter $nextTenSlots \
  --out-file $bodyFile
```

what's the right way to chain this TX in lucid , I am sure of others except ` --tx-out-datum-embed-file`

Thanks @alessandrokonrad

**Comment by alessandrokonrad** [comment]
I'm not sure what `--tx-out-datum-embed-file` does, but I assume it adds the datum to the witness set right?
Yes you can use `payToAddressWithDatum` or simply `payToContract`, which enforces you to add the datum anyway. 
`payToAddressWithDatum` is meant to add a datum to a normal pub key address for whatever reason.

**Comment by jonathanfishbein1** [comment]
In the cli it's possible to fully spend a utxo amd close it out using tx-out-datum-embed-file. However in lucid it was leaving a residual ada at the utxo along with the datum.  The was the behavior a couple months ago, I'm in the process of seeing if that's still the case

**Comment by jonathanfishbein1** [comment]
This is also possible in lucid if you dont include a payToContract method in you TX
