### ISSUE TITLE
npm commands showing errors on windows 10 command line

### ISSUE THREAD

**Issue by besiwims** [spacebudz/lucid#53]
I followed steps on how to install and run build, run test, etc  on windows 10 command line but got these errors:

C:\Users\besib>npm run build
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! Missing script: "build"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\besib\AppData\Local\npm-cache\_logs\2022-07-09T21_41_56_808Z-debug-0.log

C:\Users\besib>npm test
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! Missing script: "test"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\besib\AppData\Local\npm-cache\_logs\2022-07-09T21_42_34_864Z-debug-0.log

C:\Users\besib>npm run
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

C:\Users\besib>npm run build
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! Missing script: "build"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\besib\AppData\Local\npm-cache\_logs\2022-07-09T21_43_07_528Z-debug-0.log

C:\Users\besib>code .
'code' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\besib>cd lucid

C:\Users\besib\lucid>npm build
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
Unknown command: "build"

Did you mean this?
    npm run build # run the "build" package script

To see a list of supported npm commands, run:
  npm help

C:\Users\besib\lucid>npm run build
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> lucid-cardano@0.3.5 build
> tsdx build --format esm

'tsdx' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\besib\lucid>npm run test
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> lucid-cardano@0.3.5 test
> node --no-warnings --experimental-vm-modules node_modules/jest/bin/jest.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\besib\lucid\node_modules\jest\bin\jest.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

C:\Users\besib\lucid>npm run doc
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! Missing script: "doc"
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     npm docs # Open documentation for a package in a web browser
npm ERR!     npm run docs # run the "docs" package script
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\besib\AppData\Local\npm-cache\_logs\2022-07-09T21_45_41_321Z-debug-0.log

C:\Users\besib\lucid>npm run docs
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> lucid-cardano@0.3.5 docs
> typedoc --entryPoints ./custom_modules/cardano-multiplatform-lib-browser/cardano_multiplatform_lib.d.ts --entryPoints ./custom_modules/cardano-multiplatform-lib-nodejs/cardano_multiplatform_lib.d.ts --entryPoints src --entryPointStrategy expand --exclude '**/core/**' --exclude '**/examples/**' --plugin ./node_modules/typedoc-theme-category/dist/index.js --theme category

'typedoc' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\besib\lucid>cd C:\Users\besib\lucid\src\examples\sample-ada-transfer

C:\Users\besib\lucid\src\examples\sample-ada-transfer>npm start
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> sample-ada-transfer@1.0.0 start
> npm run build && ./node_modules/http-server/bin/http-server ./dist

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> sample-ada-transfer@1.0.0 build
> ./node_modules/webpack/bin/webpack.js

'.' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\besib\lucid\src\examples\sample-ada-transfer>npm run build
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> sample-ada-transfer@1.0.0 build
> ./node_modules/webpack/bin/webpack.js

'.' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\besib\lucid\src\examples\sample-ada-transfer>

**Comment by T1busz** [comment]
Hi! Have you found a way to solve it?
