### ISSUE TITLE
Cip30 experimental question

### ISSUE THREAD

**Issue by nejcr** [spacebudz/lucid#66]
Hello,
Correct me if I am wrong but looking at the [CIP-30](https://cips.cardano.org/cips/cip30/) `getCollateral` is no longer associated with the experimental flag as implemented in nami(Needs to be updated as well?).
Should therefore [`api.experimental.getCollateral`](https://github.com/Berry-Pool/lucid/blob/main/src/lucid/lucid.ts#L190) be replaced with  [`api.getCollateral`](https://github.com/nejcr/lucid/blob/colleteral-experimental-remove/src/lucid/lucid.ts#L195) .

**Comment by alessandrokonrad** [comment]
Yes, technically you are right. But there is no relevance for this endpoint anymore after Vasil. Lucid handles collateral on its own and doesn't require this seperate endpoint anymore. So I think it's fine to have it like this temporarily until the hard fork.
