### ISSUE TITLE
Lucid type error when trying to run simple transaction code

### ISSUE THREAD

**Issue by ssbright** [spacebudz/lucid#73]
Hello! 

I am trying to write a simple code that sends ADA, modeling it similar to your simple transaction code. Last week, I had issues running my code in Vasil, but it seemed this error was resolved. Now, I am getting an error when trying to compile my ts code. However, the error seems to be originating from the lucid code itself. Is this an error needing to be addressed here?

```tsc index.ts
node_modules/lucid-cardano/types/src/types/types.d.ts:208:5 - error TS2411: Property 'version' of type 'number' is not assignable to 'string' index type '{ [assetName: string]: NFTMetadataDetails; }'.

208     version?: number;
        ~~~~~~~


Found 1 error in node_modules/lucid-cardano/types/src/types/types.d.ts:208```

**Comment by alessandrokonrad** [comment]
Hey! Make sure you ts compiler doesn't type check the `node_module` folder. Then it should work fine.
But this line 
```
version?: number;
```
I could remove from the code and probably should. I just realized the @ts-ignore above that line is removed after building the library.

**Comment by ssbright** [comment]
Thanks for the help! How do I ignore a specific folder? Is that done in the tsconfig.json file?

**Comment by GGAlanSmithee** [comment]
I guess you solved this issue since you closed it @ssbright but for future googlers, `node_modules` can be explicitly excluded in `tsconfig.json` like:

```json
"exclude": ["node_modules"]
```
