### ISSUE TITLE
Lucid sending incorrect # of ADA

### ISSUE THREAD

**Issue by ssbright** [spacebudz/lucid#74]
Hey,

I have gotten the code to run via javascript with no errors. However, no matter what I input as lovelace amount, the transaction always sends exactly 7758450 lovelace. The number is different if I include tokens in the transaction though. Here is a snipped of my code. Are there any glaring errors here? I thought it looked similar to your simple transaction example, but unsure why the amount sending is always wrong.  

```const serverKey = process.env.POOL_KEY;
lucid.selectWalletFromPrivateKey(serverKey);
lucid.wallet.address = async () => {
    return "addr1"; //user adress
};
let address = await lucid.wallet.address();
console.log(address);
let tx = await lucid.newTx().payToAddress("addr2", { lovelace: BigInt(100000) }).complete(); //pool addres
let txSigned = await tx.sign().complete();
let hash = await txSigned.submit();
console.log('txHash:', hash);```

**Comment by georgeos** [comment]
I'm having the same issue, even using the small sample in the README.

**Comment by alessandrokonrad** [comment]
You can't use the vasil branch with Mainnet, it's not in the vasil era yet. Some protocol parameters are different on mainnet and will be changed after the hard fork.

**Comment by ssbright** [comment]
Ok, then I am assuming we just have to wait for hard fork? There would be no use in getting code to work for pre-Vasil mainnet right because it will end soon and then code must be changed again?

**Comment by alessandrokonrad** [comment]
Mainnet works with the version from the main branch. From NPM it's simply `npm install lucid-cardano`. It's a much older version, but it works with the current mainnet.
But yeah after the hard fork everything will be merged together.
