### ISSUE TITLE
gitpage docs failing

### ISSUE THREAD

**Issue by Benderjrk** [spacebudz/lucid#75]
I wanted to note that the docs aren't building. This is the local error I receive. There is a 404 on gitpages

`npm run docs

> lucid-cardano@0.3.5 docs
> typedoc --entryPoints ./custom_modules/cardano-multiplatform-lib-browser/cardano_multiplatform_lib.d.ts --entryPoints ./custom_modules/cardano-multiplatform-lib-nodejs/cardano_multiplatform_lib.d.ts --entryPoints src --entryPointStrategy expand --exclude '**/core/**' --exclude '**/examples/**' --plugin ./node_modules/typedoc-theme-category/dist/index.js --theme category

Info: Loaded plugin typedoc-theme-category/dist/index.js
Warning: NFTFile, defined at src/types/types.ts:193, is referenced by src/types/types.NFTMetadataDetails.__type.files but not included in the documentation.
Warning:
Unsupported highlight language "hs" will not be highlighted. Run typedoc --help for a list of supported languages.
target code block :
	data Data =
	  Constr Integer [Data]
	| Map [(Data, Data)]
	| List [Data]
	| I Integer
	| B BS.ByteString
	  deriving stock (Show, Eq, Ord, Generic)
	  deriving anyclass (NFData)
source files :undefined
output file :
	undefined
Info: Documentation generated at ./docs
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: EACCES: permission denied, mkdir '/assets'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/assets'
}`

**Comment by alessandrokonrad** [comment]
Hey the main branch is kinda "deprecated" at the moment. Will soon merge everything from the vasil branch in there. This is where I'm currently working at.

**Comment by Benderjrk** [comment]
@alessandrokonrad I see. Moving to deno instead. Thanks for the update.
