### ISSUE TITLE
Insufficient input in transaction when using selectWalletFromSeed

### ISSUE THREAD

**Issue by ssbright** [spacebudz/lucid#76]
Hey, I am trying to use this new function of selectWalletFromSeed so I can generate addresses using seed phrases. I replaced my previous address code with the new one in code that I can confirm works (except it still sends the wrong # of ADA, supposedly because I am running Vasil code pre-fork). 

Trouble is, with using the selectWalletFromSeed, I am unable to execute the code properly because I get the "Insufficient input in transaction" error. I am telling the code to only send 1 ADA (1000000 lovelace). When using lucid addresses, it'll send around 9 ADA. However, this new seed phrase wallet has around 44 ADA. So, I am not sure why I am getting this error. Any thoughts?

**Comment by alessandrokonrad** [comment]
selectWalletFromSeed derives only a single address. Possible you generated multiple addresses for that seed phrase?

**Comment by ssbright** [comment]
hmmm I do not believe so. What makes you think that? I am worried that, like the other code, it is sending the wrong amount of ADA, and in this case it is more ADA than even exists in my wallet. Here is a snipped of the code, let me know if you think I am making multiple addresses.

```lucid.selectWalletFromSeed(process.env.DUSERSEED)
let address = await lucid.wallet.address();
console.log(address);
let tx = await lucid.newTx().payToAddress("address_of _poolxxxxxxx", { lovelace: BigInt(1000000) }).complete(); //pool addres
let txSigned = await tx.sign().complete();
let hash = await txSigned.submit();
console.log('txHash:', hash);

**Comment by alessandrokonrad** [comment]
Because of the "insufficient input in transaction" error. Do you use the seed phrase from an actual wallet?
Have you checked `lucid.wallet.getUtxos()`? Then you know what your real balance is.

**Comment by ssbright** [comment]
Found the issue! Thanks for suggestion. It was because the funds in wallet were not at the specified address that lucid generated. Is there a function that searches all address from seed and finds an address with enough UTXOs/funds?

**Comment by alessandrokonrad** [comment]
There is no function for that. Multiple addresses add unnecessary complexity and require you to fetch the utxos for each individually, which could slow down things a lot.
