### ISSUE TITLE
Pass lucid to backend

### ISSUE THREAD

**Issue by albertorizzi** [spacebudz/lucid#78]
I want to create tx object on Node js backend, but I need lucid object.

How can I pass lucid from frontend to backend?

**Comment by alessandrokonrad** [comment]
Hey I'm not sure what you mean with passing lucid from fronend to backend. You can run Lucid as library in Node.js or Deno for backend stuff and you can run Lucid also in the browser for frontend.

**Comment by albertorizzi** [comment]
I close issue, the answer is here #54
