### ISSUE TITLE
[Question] is there any way to integrate nami wallet with a Plutus StateMachine ?

### ISSUE THREAD

**Issue by ahaxu** [spacebudz/lucid#79]
Is there any way to integrate nami wallet with a Plutus StateMachine ?

For eg this off chain code 
```
submitContract
    :: forall s. SubmitParams
    -> Contract (Last ThreadToken) s Text ()
submitContract sp = do
    logInfo @P.String "submitting result ..."
    pkh <- Contract.ownFirstPaymentPubKeyHash
    let xp =
            AxuParams
                { athletePkh = pkh
                , axuPkh = spXPkh sp
                , lockAmount = spLockAmount sp
                , redeemDeadline = spRedeemDeadline sp
                , gameDeadline = spGameDeadline sp
                , gToken = spToken sp
                }
        client = axuSMClient xp
        sKm = spSubmittedKm sp

    m <- mapError' $ getOnChainState client
    case m of
        Nothing -> logInfo @P.String "no running game found"
        Just (getStateData -> ts, _) -> case ts of
            AxuDatum tKm Nothing -> do
                -- logInfo @P.String $ P.show i
                logInfo @P.String $ "found targetKm set " P.<> P.show tKm
                rs <- mapError' $ runStep client $ SubmitAction sKm
                case rs of
                    TransitionSuccess s ->
                        logInfo @P.String $ "transition success with new state " P.<> P.show s
                    TransitionFailure InvalidTransition{tfState = ms, tfInput = i'} -> do
                        logInfo @P.String $ "TransitionFailure !!!"
                        logInfo @P.String $ "action " P.<> P.show i'
                        case ms of
                            Nothing -> logInfo @P.String "nothing in state "
                            Just s' -> logInfo @P.String $ "current state " P.<> P.show s'

                logInfo @P.String "sumitted!"
            _ -> logInfo @P.String "unexpected datum"

```

I dont know how to convert this into js script
```
    m <- mapError' $ getOnChainState client
```
and
```
    rs <- mapError' $ runStep client $ SubmitAction sKm
```

Thank you!

**Comment by alessandrokonrad** [comment]
It's difficult to replicate that one by one. But these state machines are simply a high level API. I'm not sure how they work exactly, where do you define the on-chain validator and where do you pass it to the state machine?

**Comment by ahaxu** [comment]
This is the **onchain** validator code
https://gist.github.com/ahaxu/ad5b88d465fc0b9f59533ba1a6258c2d

This is the **offchain** part where i passed to the state machine
https://gist.github.com/ahaxu/020c1efd75ef1cd1797e8952b3eef51d

**Comment by jonathanfishbein1** [comment]
At the moment I'm trying to figure out how to interact with a state machine from the cardano-cli, then I was going to extrapolate to lucid

**Comment by ahaxu** [comment]
> 
At the moment I'm trying to figure out how to interact with a state machine from the cardano-cli, then I was going to extrapolate to lucid

if you don't mind, can you share the `cardano-cli` here. Thank you!

**Comment by jonathanfishbein1** [comment]
Looks like you can't use the runStep functionality but you can interact with state machine contracts as if they regular ones.  Just providing the necessary script-file, datum and redeemer

**Comment by ahaxu** [comment]
> 
Looks like you can't use the runStep functionality but you can interact with state machine contracts as if they regular ones. Just providing the necessary script-file, datum and redeemer

if so, i can make a try, thank you guys for your suggestion.
