### ISSUE TITLE
[Question] is refactoring and additional testing welcomed? 

### ISSUE THREAD

**Issue by IlmariKu** [spacebudz/lucid#82]
I'm a TS-dev by my day job and am a big fan @alessandrokonrad's work in the Cardano ecosystem. 

I've been trying to learn Haskell and Plutus, but I've never really found the time for it to start from scratch. I've heard about the Lucid-library and found it as a cool way of understanding Plutus and Cardano more.

I don't think I can participate in actual development, due to my lack of understanding of Plutus, but I'd be interested in just starting from the bottom. Refactoring and writing unit-tests for the existing Lucid-codebase. 

As an example for refactoring, I found `main/src/plutus/data.ts` to be quite confusing with all the long "if"-clauses.

Is this something that would be useful for the project?

**Comment by alessandrokonrad** [comment]
Hey! For sure, feel free to make PRs. Although the code is kinda "clean" overall imo, some refactoring and other cleanups can surely be done. More testing is definitely welcomed.

**Comment by GGAlanSmithee** [comment]
@IlmariKu 

I would **love** for the onboarding / setup story to be improved. For me, as a newcomer to the Cardano dev ecosystem, lucid is, by far, the simplest way to get started from a application PoV. Having said this, it's not super easy to get setup with the project/repository itself. I think this stems from two issues:

* Usage of deno
* Lack of documentation

I don't think either of these points is really a problem - but - trying to set this up locally, things did _just work_, which would be nice. While I could build the code, I could not run the examples or the tests.

**Comment by alessandrokonrad** [comment]
Agreed, it can be improved.
But Deno is super easy to use actually and doesn't have all this bloat NPM has. You have pretty much everything built into the `deno` binary, from running, to testing, to formatting etc.

> I could not run the examples or the tests.
Curious what was the issue here? Or why were you no able to run them?

**Comment by GGAlanSmithee** [comment]
@alessandrokonrad 

Yeah, I really do like deno as a concept, just never really got into it (yet). Will give it a bit more time though.

Regarding the issues, it was the ones I reported in https://github.com/spacebudz/lucid/pull/108:

> Unfortunatley, I wasn't able to test this locally, because the package would not resolve when installting it from a local folder. Not sure what was going on, since this usually work. I also could not get the examples to work with the error TypeError: Cannot convert undefined to a BigInt. I couldn't run the tests either, with the error error: TS2503 [ERROR]: Cannot find namespace 'Core'. so I guess there is something wrong in my setup. I'm not used to deno, so might be something related to that.

Or more succintly:

## Testing

* command: `deno test ./tests/mod.test.ts`
* result: `error: TS2503 [ERROR]: Cannot find namespace 'Core'`

## Example
command: `deno run --allow-read --allow-net always_succeeds.ts`
* result: `error: Uncaught (in promise) TypeError: Cannot convert undefined to a BigInt`

**Comment by alessandrokonrad** [comment]
You need to: `deno test --allow-env --allow-read --allow-net tests`.
It's defined in the deno.json file. For convenience you can also run `deno task test` simply.
If you don't allow env then the wasm module cannot be loaded. 

Deno opposed to Node.js only allows you to run certains things if you actively allow them. It makes it much more secure. If you don't care at all and trust the software anyway, you can just do `deno run -A ...`. The -A flag enables everything.

**Comment by GGAlanSmithee** [comment]
Thanks @alessandrokonrad. I did know about the allow flags of deno, but not that env variables also requires permission, but it makes sense. Will test again as soon as I'm able to.
