### ISSUE TITLE
Invalid Character error while using Lucid

### ISSUE THREAD

**Issue by ssbright** [spacebudz/lucid#83]
Hello, was wondering if you have encountered this error before, and why lucid is throwing it at me. I am trying to use the payToAddress function but with a variable for address. Here is relevant code. 

```
lucid.selectWalletFromSeed(process.env.POOLSEED)
    let address = await lucid.wallet.address();
    let token = "<sometokenID>";
    let tx = await lucid.newTx().payToAddress(addressC, { lovelace: BigInt(1000000), [token]: BigInt(5) }).complete();
```

error I get:  error invalid character (code=")

**Comment by alessandrokonrad** [comment]
I recommend you to log the variables you use there.  The `token` variable could be wrong as well.

**Comment by ssbright** [comment]
This is what I get when I log the address and token. Are there supposed to be quotes around the address?

```
inputAddress "addr1q87t0w6aex59ve5j73pr9cpy94uras8julnwdv6qx9mwanutt68365g6lg6jyc4fvq24jesf3d68wy76hu7fjk2a34ssqcwhnk"
string
token cf85feeae10e8f6d36d265e2310045a4afc38319a779232e5dfff2466e65774c50
string
```

**Comment by rodrigomd94** [comment]
Seems like you have a typo. You wrote `addressC` instead of `address`
`let tx = await lucid.newTx().payToAddress(addressC, { lovelace: BigInt(1000000), [token]: BigInt(5) }).complete();`

**Comment by ssbright** [comment]
Thanks for the advice, but that wasn't a type. That is how I defined the input, it stands for addressC(ustomer).

Here is more of the code

```
async function sendToken(addressC, sentADA) {
  try{

    lucid.selectWalletFromSeed(process.env.POOLSEED)
    let address = await lucid.wallet.address();
    let token = "cf85feeae10e8f6d36d265e2310045a4afc38319a779232e5dfff2466e65774c50" 
    let tx = await lucid.newTx().payToAddress(addressC, { lovelace: BigInt(1000000), [token]: BigInt(5) }).complete(); //customer addres
    let txSigned = await tx.sign().complete();

    let hash = await txSigned.submit();
  } catch (error) {
    console.log("this is my error", error)
  }


};
```

**Comment by rodrigomd94** [comment]
Oh sorry I misunderstood not having looked at the full function.  Hmm transaction looks good, have you tried logging the process.env.POOLSEED? Or remove the try-catch to see which line is the problem.

**Comment by ssbright** [comment]
The code works when I replace the addressC with a address in quotes. So I am sure the POOLSEED .env is working. Also I have used console.log and am nearly certain the error is the "let tx = " line

**Comment by ssbright** [comment]
I ended up solving this by removing the double quotes within the variable. Thanks everyone!
