### ISSUE TITLE
Do you need to enforce wallet account to use single address mode when using our app?

### ISSUE THREAD

**Issue by BenjaminGrabow** [spacebudz/lucid#86]
Hey @alessandrokonrad, I hope you're having a great day!
 We implemented Lucid into our Dapp and were wondering if we need to enforce the single address mode on for example Eternl.

Problem is: for users with wallet accounts that have multiple addresses we can't load the correct amount of tokens or ADA they're holding (because they're split into multiple addresses). This is not only a problem for loading the number of tokens but also for sending a transaction. 

Loading the wallet with Lucid just returns a single address and that's it (it doesn't load all addresses from the wallet account). Is there any other known way to do this, or we're simply limited and need to enforce that users use the single address mode to be able to use our Dapp?

**Comment by alessandrokonrad** [comment]
Hey, Lucid should give you the entire utxo set of all addresses with `lucid.wallet.getUtxos()`. It queries them directly from the wallet via the dApp connector. Lucid doesn't limit you to single address wallets no. But yes Lucid shows you only a single "primary" address for receiving change and other things.

**Comment by BenjaminGrabow** [comment]
Thanks a lot for the fast response @alessandrokonrad! You doing great work which is a massive help for the project I'm working on. Just got everything working with the mentioned approach - will close this issue now.

**Comment by BenjaminGrabow** [comment]
What I thought would be possible is sending all tokens to the primary address and executing the final tx (with all 1000 tokens) from the primary address. But this would result in multiple messages the user has to sign and would be a horrible UX. There must be some other way right?

**Comment by BenjaminGrabow** [comment]
Just found it - function `collectFrom`. This thread is a nice monologue lol.
