### ISSUE TITLE
Not allowed to load local resources in chrome

### ISSUE THREAD

**Issue by rahpal** [spacebudz/lucid#90]
<img width="1775" alt="Screenshot 2022-10-07 at 2 23 15 AM" src="https://user-images.githubusercontent.com/8003075/194416627-5dd375d0-1194-447e-969c-70a82386e8e7.png">

How to resolve this error???
I am using angular 14, node v14 and npm 6.

**Comment by GGAlanSmithee** [comment]
There is probably a problem with your setup in terms of your bundler (webpack etc). Do you have a reproduction repository?
