### ISSUE TITLE
broken Discord link in README

### ISSUE THREAD

**Issue by GGAlanSmithee** [spacebudz/lucid#93]
Sorry about opening an issue about this, but the Discord link in the README seems to be broken.

**Comment by alessandrokonrad** [comment]
Hey what happens when you click on the link? It's working for me, but maybe because I'm part of the Discord group already.

**Comment by GGAlanSmithee** [comment]
It opens discord, but doesn't load the channel. I get an error message in the lines of "You find yourself in a strange place, you don't have access to any textchannels, or there aren't any on this server".

The discord link is https://discord.com/channels/824711383185621082

![image](https://user-images.githubusercontent.com/11805103/195435892-48d94be9-9123-42c7-ad6a-415101878cf1.png)

**Comment by GGAlanSmithee** [comment]
I paraphrased the message since it's in my native tounge

**Comment by alessandrokonrad** [comment]
Hey lemme know if the new invite link works

**Comment by GGAlanSmithee** [comment]
It sure does @alessandrokonrad 

![image](https://user-images.githubusercontent.com/11805103/196402279-8243043f-3ccc-47e8-8ed6-848a8fbe1d5c.png)
