### ISSUE TITLE
Preprod Slot Config is subtly incorrect

### ISSUE THREAD

**Issue by TotallyNotChase** [spacebudz/lucid#96]
There's a bit of a subtle bug in the slot config used currently for preprod.

https://github.com/spacebudz/lucid/blob/39cd2129101bd11b03b624f80bb5fe3da2537fec/src/plutus/time.ts#L10-L15

The system start for preprod _is_ correct. However, the network started with slot length at 20 before shelley era. It only transitioned to slot length of 1 at shelley era. This is why the calculations with `slotZero = 0, zeroTime = 1654041600000, slotLength = 1` don't give proper results.

The offset of `1641599000` sort of fixes this for slots after `86400` (shelley era beginning) - but I suspect the error will add up as time goes by.

Instead, `zeroTime` should be kept the official system start (plus `1728000`), but `slotZero` ought to be changed to `86400`.

Here's what the era history for preprod looks like currently (consolidated for brevity):
https://gist.github.com/TotallyNotChase/a90d91744500c353f84755237188efc5

All time values are in seconds.

**Comment by TotallyNotChase** [comment]
I haven't checked yet, but is this also the case for preview? Did that also start with 20s slot lengths?

In any case, this ought to be more robust if the calculation was done with the full era history at hand. Similar to how `cardano-api` does it. Alas, obtaining the era history dynamically is rather tricky as Blockfrost does not yet support it. I've been informed that they might support such an endpoint soon though.

**Comment by TotallyNotChase** [comment]
> I haven't checked yet, but is this also the case for preview? Did that also start with 20s slot lengths?

I just checked and preview has quite the peculiar era history. But the gist of it is that it started "directly" at alonzo, with slot length 1.

**Comment by alessandrokonrad** [comment]
> Instead, `zeroTime` should be kept the official system start (plus `1728000`), but `slotZero` ought to be changed to `86400`.

Where does`1728000` come from?

> I just checked and preview has quite the peculiar era history. But the gist of it is that it started "directly" at alonzo, with slot length 1.

Yeah I'm a bit confused too, but Preview seems to work fine with the current setting, as well as Mainnet and Testnet.
Only Preprod is off, but probably fine also with your suggestion now.

**Comment by TotallyNotChase** [comment]
> Where does `1728000` come from?

It's the start of the shelley era and end of the byron era (from which point slot length got set to 1).  Note that this is in seconds.
https://gist.github.com/TotallyNotChase/a90d91744500c353f84755237188efc5#file-eras-json-L33

The shelley era start time is then: 1654041600s + 1728000s
The shelleya era starting slot is: 86400

**Comment by alessandrokonrad** [comment]
Should be resolved now with Lucid 0.6.7
