### ISSUE TITLE
Could not serialize the data: Error: Could not serialize the data: Error: encoding/hex: invalid byte: o

### ISSUE THREAD

**Issue by rahpal** [spacebudz/lucid#98]
`const map1 = new Map();
    map1.set('owner', paymentCredential?.hash);
    // This represents the Datum struct from the Helios on-chain code
    const datum = Data.to(
      //new Constr(0, [new Constr(0, [paymentCredential?.hash!])]), 
      map1
    );`
    
    This is my code for Datum

**Comment by alessandrokonrad** [comment]
You cannot do `map1.set('owner' ...`. `owner` is utf-8 encoded, but needs to be hex encoded here.
