### ISSUE TITLE
 Error: Wallet could not send the tx. Getting mentioned error while transferring multi-asset token using lucid-cardano package in react

### ISSUE THREAD

**Issue by SevenbitsShubham** [spacebudz/lucid#99]
While transferring cardano token using lucid-cardano in react with Nami wallet I am getting the below error:
{
“code”: 2,
“info”: “Wallet could not send the tx.”,
“message”: “"transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (UtxoFailure (BabbageOutputTooSmallUTxO [((Addr Mainnet (KeyHashObj (KeyHash \"10ba0915f02317ef10ff0310e93f8da9ae045e2537b667767dd87036\")) (StakeRefBase (KeyHashObj (KeyHash \"d659ae147a1c297b1e55236f8e8b10da629bb4835f5a51e186d8213c\"))),Value 168090 (fromList [(PolicyID {policyID = ScriptHash \"64700329d616f20f4e83f2bc579513fca51646d47466a97f8fd1c229\"},fromList [(444958,998)])]),NoDatum,SNothing),Coin 1142150)]))])"”
}

code:
export const buildSendTokenTransactionFromAdmin = async(lucid,amount,requiredBeneficiaryAddr) =>{
let tx = await lucid.newTx()
.payToAddress(requiredBeneficiaryAddr,
{
“64700329d616f20f4e83f2bc579513fca51646d47466a97f8fd1c229444958”: BigInt(amount)
}
)
.complete();

const signedTx = await tx.sign().complete();

const txHash = await signedTx.submit();

console.log(txHash);
return txHash

**Comment by alessandrokonrad** [comment]
Hey what Lucid version are you on?

**Comment by alessandrokonrad** [comment]
That version is outdated and broken since the vasil upgrade. Check out the latest version 0.6.7
